# Generated by Django 4.2 on 2026-04-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lycee', models.CharField(blank=True, max_length=200)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_pack', models.CharField(choices=[('annuel', 'Pack annuel'), ('semestriel', 'Pack semestriel'), ('trimestriel', 'Pack trimestriel'), ('chapitre', 'Pack chapitre'), ('exercices', 'Pack exercices'), ('bac', "Pack résolution d'épreuves")], default='annuel', max_length=20)),
                ('est_visible', models.BooleanField(default=True)),
                ('matieres', models.ManyToManyField(related_name='packs', to='courses.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_video', models.CharField(choices=[('cours', 'Cours'), ('exercice', 'Exercice corrigé'), ('bac', "Correction d'épreuve")], default='cours', max_length=20)),
                ('duree', models.CharField(blank=True, max_length=20)),
                ('url_hebergement', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.enseignant')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('annees', models.ManyToManyField(related_name='specialites', to='courses.annee')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PackVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0)),
                ('est_video_explicative', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.pack')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.video')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('pack', 'video')},
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='videos',
            field=models.ManyToManyField(related_name='packs', through='courses.PackVideo', to='courses.video'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='specialites',
            field=models.ManyToManyField(related_name='matieres', to='courses.specialite'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='courses.matiere'),
        ),
    ]
