# Generated by Django 6.0.4 on 2026-04-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='matieres',
        ),
        migrations.AddField(
            model_name='pack',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='courses.annee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='courses.matiere'),
            preserve_default=False,
        ),
    ]
