# Generated by Django 6.0.4 on 2026-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_pack_matieres_pack_annee_pack_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='est_nouveau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='est_populaire',
            field=models.BooleanField(default=False),
        ),
    ]
