# Generated by Django 6.0.4 on 2026-05-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_pack_est_nouveau_pack_est_populaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='specialite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='courses.specialite'),
            preserve_default=False,
        ),
    ]
